Ignore error from condor log dir create
Whenever `condor.py` submits a new job, it creates the log directory with
`os.makedirs()`. This works fine the first time, but on subsequent batch
submits during the same run, the log directory will already exist. This
causes errors like:

```
2018-Nov-13 12:22:29 INFO Submitted batch 'defimgs' (id=11, #jobs=468, #tasks=1871)
2018-Nov-13 12:23:40 WAIT 287 pending, 174 running, 0 suspended, 0 held, 7 completed
2018-Nov-13 12:39:15 DONE 468 succeeded, 0 failed
2018-Nov-13 12:39:15 INFO Average images at observed time points (step=0)
Traceback (most recent call last):
  File "/homes/jcupitt/mirtk/lib/tools/construct-atlas", line 147, in <module>
    atlas.construct(start=args.start, niter=args.steps - args.start)
  File "/homes/jcupitt/mirtk/lib/python/mirtk/atlas/spatiotemporal.py", line 1113, in construct
    job = self.avgimgs(step=step - 1, force=force, queue=queue["short"])[0]
  File "/homes/jcupitt/mirtk/lib/python/mirtk/atlas/spatiotemporal.py", line 1047, in avgimgs
    job = self._submit(batchname, script=script, tasks=tasks, step=step, queue=queue)
  File "/homes/jcupitt/mirtk/lib/python/mirtk/atlas/spatiotemporal.py", line 224, in _submit
    workdir=workdir, verbose=0)
  File "/homes/jcupitt/mirtk/lib/python/mirtk/batch/condor.py", line 48, in submit
    os.makedirs(logdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/homes/jcupitt/GIT/brain-atlas/andreas-atlas-early/output/dhcp-w29-35-adaptive-sigma_1.00-nmi/cache/i00/log'
```

This patch simply ignores OS errors from makedirs. You could test for
dir exists first, but then of course they could be a race. This seemed
the easest and safest.